<a href="https://colab.research.google.com/github/ShireenKachroo/PyTorch-Practice/blob/main/PyTorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import torch
import torch.nn as nn
import torch.optim as optim

In [31]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [32]:
iris = load_iris()

In [35]:
X = iris.data    # features for each flower (sepal len, sepal width etc)
y = iris.target  # labels/ classes  (0: seprosa, 1: versicolr , 2: virginica)

print(X[:5])
print("=====")
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
=====
[0 0 0 0 0]


In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # split dataset into 80-20

In [37]:
# feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
# convert to tensors

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [40]:
# BUild NN

class IrisModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(4, 8)  # 4 i/p, 8 hidden layers
        self.relu = nn.ReLU()     # activation func = ReLU
        self.fc2 = nn.Linear(8, 3)  # 8 hidden layers, 3 o/p ===> 3 flower classes

    def forward(self, x):

        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)

        return x

In [41]:
model = IrisModel()
print(model)

IrisModel(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=8, out_features=3, bias=True)
)


In [42]:
# loss func
criterion = nn.CrossEntropyLoss()

In [43]:
# optimzer
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [45]:
# training loop

epochs = 100

for epoch in range(epochs):

    outputs = model(X_train)   # fwd pass

    loss = criterion(outputs, y_train)   # loss calc

    optimizer.zero_grad()  # prev gradients clean

    loss.backward()   # bakprop

    optimizer.step()  # weights update

    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [10/100], Loss: 0.1063
Epoch [20/100], Loss: 0.0956
Epoch [30/100], Loss: 0.0872
Epoch [40/100], Loss: 0.0806
Epoch [50/100], Loss: 0.0753
Epoch [60/100], Loss: 0.0709
Epoch [70/100], Loss: 0.0675
Epoch [80/100], Loss: 0.0647
Epoch [90/100], Loss: 0.0623
Epoch [100/100], Loss: 0.0602


In [46]:
with torch.no_grad():

    predictions = model(X_test)

    predicted_classes = torch.argmax(predictions, dim=1)

    accuracy = (predicted_classes == y_test).float().mean()

    print("Accuracy:", accuracy.item())

Accuracy: 1.0


# understanding basic syntax

In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


In [3]:
# TENSOR = DS like numpy Arrays ====> but only for NUMERIC data (INT/FLOAT/ BOOL)

import torch
arr = torch.tensor([1,2,3,4,5])
print(arr)

tensor([1, 2, 3, 4, 5])


In [6]:
print(arr.dtype)
print(arr.shape)

torch.int64
torch.Size([5])


In [9]:
matrix = torch.tensor(
    [[1,2], [3,4]]
)

In [13]:
print(matrix.shape)

torch.Size([2, 2])


In [12]:
a = torch.tensor([1,2,3])
b = torch.tensor([5,0,3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([6, 2, 6])
tensor([-4,  2,  0])
tensor([5, 0, 9])
tensor([0.2000,    inf, 1.0000])


In [17]:
x = torch.tensor([1,2,3,4])
x.reshape(2,2)

tensor([[1, 2],
        [3, 4]])

In [18]:
import torch.nn as nn

In [19]:
layer = nn.Linear(2,1)  # 2i/p features and 1 o/p feature

In [20]:
#fwd pass
x = torch.tensor([[1.0,2.0]])
output = layer(x)
print(output)

tensor([[-0.1429]], grad_fn=<AddmmBackward0>)


In [22]:
relu = nn.ReLU()
print(relu(x))

tensor([[1., 2.]])


In [24]:
# simple nn
model = nn.Sequential(
    nn.Linear(2,4), # input 2, 4 hidden layers
    nn.ReLU(),
    nn.Linear(4,1)  # 4 hidden layers===> 1 o/p
)

In [25]:
# loss function ===> how much ERROR

# 1 REGRESSION
criterion = nn.MSELoss()

# 2 CLASSIFICATION
criterion = nn.CrossEntropyLoss()

In [26]:
# Optimizers = updates weights
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [27]:
# training loop
for eopch in range(100):  # 1 epoch = full dataset prr 1 baar train,   batch size = no of samples processed together at a time
  predictions = model(x)  #fwd pass
  loss = criterion(predictions,y)  # loss func ---> error calc
  optimizer.zero_grad()  # old gradients--->clear
  loss.backward()  # backpropagation
  optimizer.step()      # weights update

In [ ]:
# model.train() = training mode
# model.eval() = inference/ testing mode