In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cpu
False


In [3]:
# TENSOR = DS like numpy Arrays ====> but only for NUMERIC data (INT/FLOAT/ BOOL)

import torch
arr = torch.tensor([1,2,3,4,5])
print(arr)

tensor([1, 2, 3, 4, 5])


In [6]:
print(arr.dtype)
print(arr.shape)

torch.int64
torch.Size([5])


In [9]:
matrix = torch.tensor(
    [[1,2], [3,4]]
)

In [13]:
print(matrix.shape)

torch.Size([2, 2])


In [12]:
a = torch.tensor([1,2,3])
b = torch.tensor([5,0,3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([6, 2, 6])
tensor([-4,  2,  0])
tensor([5, 0, 9])
tensor([0.2000,    inf, 1.0000])


In [17]:
x = torch.tensor([1,2,3,4])
x.reshape(2,2)

tensor([[1, 2],
        [3, 4]])

In [18]:
import torch.nn as nn

In [19]:
layer = nn.Linear(2,1)  # 2i/p features and 1 o/p feature

In [20]:
#fwd pass
x = torch.tensor([[1.0,2.0]])
output = layer(x)
print(output)

tensor([[-0.1429]], grad_fn=<AddmmBackward0>)


In [22]:
relu = nn.ReLU()
print(relu(x))

tensor([[1., 2.]])


In [24]:
# simple nn
model = nn.Sequential(
    nn.Linear(2,4), # input 2, 4 hidden layers
    nn.ReLU(),
    nn.Linear(4,1)  # 4 hidden layers===> 1 o/p
)

In [25]:
# loss function ===> how much ERROR

# 1 REGRESSION
criterion = nn.MSELoss()

# 2 CLASSIFICATION
criterion = nn.CrossEntropyLoss()

In [26]:
# Optimizers = updates weights
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [27]:
# training loop
for eopch in range(100):  # 1 epoch = full dataset prr 1 baar train,   batch size = no of samples processed together at a time
  predictions = model(x)  #fwd pass
  loss = criterion(predictions,y)  # loss func ---> error calc
  optimizer.zero_grad()  # old gradients--->clear
  loss.backward()  # backpropagation
  optimizer.step()      # weights update

In [ ]:
# model.train() = training mode
# model.eval() = inference/ testing mode